### ISSUE TITLE
IP address not assigned

### ISSUE THREAD

**Issue by fabiofusco-rre** [davidramosweb/hassio-addons#2]
Hi, I followed your instructions, but my devices can not get the ip address.

I disable other DHCP add-ons, but with no luck.

My hassio is has an address like 192.168.1.x, maybe should I change the 'address' value in your configuration from "address": "192.168.99.1" to something different?

Just let you know that this add-on has great opportunities: if it works could be very interesting!!
Thanks in advance,
Fabio

**Comment by MahrWe** [comment]
Hi Fabio, 

The hostapd addon does not provide any dhcp functionality. You have some options to got from here.
1.) You could set a static IP in each of your connecting clients this should match the address of your access point e.g. 192.168.99.2-255 in case of the sample configuration.
2.) You can use the Core-Addon Simple-DHCP found in the AddonStore or on github <https://github.com/home-assistant/hassio-addons/tree/master/dhcp_server> 
the minimal configuration for DHCP-Server could look like this to match sample config of hostapd:
{
  "domain": "mynetwork.local",
  "dns": ["8.8.8.8", "8.8.4.4"], # not needed because not routing to internet exists
  "default_lease": 86400,
  "max_lease": 172800,
  "networks": [
    {
      "subnet": "192.168.99.0",
      "netmask": "255.255.255.0",
      "range_start": "192.168.99.100",
      "range_end": "192.168.99.200",
      "broadcast": "192.168.99.254",
      "gateway": "192.168.99.1",
      "interface": "wlan0"
    }
  ],
  "hosts": []
}

Best,
MahrWe
