### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by sh4rkt3ch** [davidramosweb/hassio-addons#7]
20-01-02 16:56:18 ERROR (SyncWorker_15) [hassio.docker.addon] Can't build 567c2022/armv7-addon-hassio-hostapd:1.0.2: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.18.1-r2 net-tools=1.60_git20140218-r2 sudo=1.8.27-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 2

HA         0.103.4
HassOS  2.12

**Comment by sebviel** [comment]
Hi,

Confirming same issue on a RPI 3 B+ fresh installed :

20-01-03 03:27:55 ERROR (SyncWorker_3) [hassio.docker.addon] Can't build 567c2022/armv7-addon-hassio-hostapd:1.0.2: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.18.1-r2 net-tools=1.60_git20140218-r2 sudo=1.8.27-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 2

version | 0.103.5
System | HassOS 3.7

2020/01/06 - UPD :
Seems that sources has been changed since last code revision:

apk update && apk add --no-cache bash jq iw hostapd networkmanager=**1.20.8-r0** net-tools=1.60_git20140218-r2 sudo=**1.8.29-r0** && rm -rf /var/cache/apk/

The last command launched in a ssh return no errors and confirm hostapd (2.9-r1) and iw (5.4-r0) installed.

Please correct script and confirm us once tested again.

Thanks..

**Comment by MahrWe** [comment]
This issue should be fixed by the version-bump of some packages in the commit by sebviel #8 until the pull request is accepted you can use sebviels or my fork to test and send feedback.

**Comment by moverperfect** [comment]
Hi, I tried the patch-1 branch in @sebviel fork as well as the @MahrWe master fork and I am also getting an issue, this time the non-zero code is 1.

Can't build local/aarch64-addon-hassio-hostapd:1.0.3: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.20.8-r0 net-tools=1.60_git20140218-r2 sudo=1.8.29-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by Emilio-IT** [comment]
Hi,
Hassio on Docker running on Raspberry Pi 3B, Home Assistant version 0.106.3.

Tried to install Hassio Hostapd add-on getting _Failed to install addon, Unknown Error, see logs_ result. My system log was stating `Can't build 567c2022/armv7-addon-hassio-hostapd:1.0.2: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.18.1-r2 net-tools=1.60_git20140218-r2 sudo=1.8.27-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 2` as already mentioned by others.

Then I've opened Hassio SSH and launched `apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.20.8-r0 net-tools=1.60_git20140218-r2 sudo=1.8.29-r0 && rm -rf /var/cache/apk/` as suggested by @sebviel (thanks for good hint!). After successful fetching few .tar.gz, execution stopped stating
```
ERROR: unsatisfiable constraints:
  sudo=1.8.31-r0
    breaks: world[sudo=1.8.29-r0]
```
So I slightly changed last command by writing this **1.8.31-r0** version (as read in last error message). Finally new command `apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.20.8-r0 net-tools=1.60_git20140218-r2 sudo=1.8.31-r0 && rm -rf /var/cache/apk/` was ending properly.

 @davidramosweb: I'm eager to try your add-on. Could you please fix this issue? Thanks in advance.

**Comment by daniel-sjodin** [comment]
Hi, 
@Emilio-IT based on your suggested change to ** 1.8.31-r0** I have made a fork and updated the dockerfile. I have successfully tested on HassOS 3.12. Go ahead and try :)

**Comment by davidramosweb** [comment]
Hi, I have made an update. 
Thanks.
